In [1]:
import numpy as np

In [29]:
def get_nv(a, b, c):
    ab = b-a
    ac = c-a
    
    n = np.ones([2,3])
    n[0,:] = ab
    n[1,:] = ac
    x1 = n[0,1]*n[1,2] - n[1,1]*n[0,2]
    y1 = n[0,2]*n[1,0] - n[1,2]*n[0,0]
    z1 = n[0,0]*n[1,1] - n[1,0]*n[0,1]
    
    nv = [x1, y1, z1]
    return nv    

In [34]:
a = np.array([1,0,0])
b = np.array([0,1,0])
c = np.array([0,0,1])

nv = get_nv(a, b, c)
nv

[1.0, 1.0, 1.0]

In [36]:
def cs_transf(nv, x, y, z):
   pass

In [84]:
o_cs = np.matrix([[1.0],[1.0],[1.0]])
print(o_cs)

l_nv = np.sqrt(nv[0]**2 + nv[1]**2 + nv[2]**2)
l_nv

[[1.]
 [1.]
 [1.]]


1.7320508075688772

In [85]:
cosx = x/l
sinx = np.sqrt(nv[1]**2+nv[2]**2)/l_nv
cosy = y/l_nv
siny = np.sqrt(nv[0]**2+nv[2]**2)/l_nv
cosz = z/l_nv
sinz = np.sqrt(nv[0]**2+nv[1]**2)/l_nv

In [86]:
x_rotate = np.matrix([[1,0,0],[0,cosx,sinx],[0,-sinx,cosx]])
y_rotate = np.matrix([[cosy,0,-siny],[0,1,0],[siny,0,cosy]])
z_rotate = np.matrix([[cosz,sinz,0],[-sinz,cosz,0],[0,0,1]])
print(x_rotate)
print(y_rotate)
print(z_rotate)

[[ 1.          0.          0.        ]
 [ 0.          0.57735027  0.81649658]
 [ 0.         -0.81649658  0.57735027]]
[[ 0.57735027  0.         -0.81649658]
 [ 0.          1.          0.        ]
 [ 0.81649658  0.          0.57735027]]
[[ 0.57735027  0.81649658  0.        ]
 [-0.81649658  0.57735027  0.        ]
 [ 0.          0.          1.        ]]


In [94]:
prime_cs = z_rotate*y_rotate*x_rotate*o_cs
x_prime, y_prime, z_prime = prime_cs[:]
print(prime_cs)

[[1.58413917]
 [0.17390246]
 [0.67842539]]


In [157]:
data = np.loadtxt(r'C:\Users\BZMBN4\Desktop\GE2-17.6', delimiter=',',skiprows=2)
x = data[:,1]
y = data[:,2]
z = data[:,3]
v = data[:,4]

In [318]:
z_divide = np.linspace(min(z), max(z), 5, endpoint=True)
y_divide = np.linspace(min(y), max(y), 5, endpoint=True)
z_divide[-1] += 0.1 
y_divide[-1] += 0.1 
print(z_divide)
print(y_divide)

[0.76557314 0.81436852 0.86316389 0.91195926 1.06075463]
[0.64770007 0.68520007 0.72270006 0.76020005 0.89770005]


In [319]:
import pandas as pd

gridy =[]
for i in range(len(x_divide)-1):
    gridy.append(data[(y >= y_divide[-(i+2)]) & (y < y_divide[-(i+1)])])
    print(len(gridy[i]))

1498
1978
1941
1456


In [367]:
grid = []
avg_grid = np.ones([4,4])
number = np.ones([4,4])
vmax = np.ones([4,4])
vmin = np.ones([4,4])
zone_number = np.linspace(1,16,16)
zone_number = zone_number.reshape(4,4)
j = 0
for row in gridy:
    for i in range(len(z_divide)-1):        
        cell = row[(row[:,3]>=z_divide[i]) & (row[:,3] < z_divide[i+1])]
        grid.append(cell)
        avg_grid[j, i] = np.mean(cell[:,4])
        number[j, i] = len(cell[:,1])
        vmax[j, i] = max(cell[:,4])
        vmin[j, i] = min(cell[:,4])
    j += 1
grid = np.reshape(grid, [4,4])
grid[0,0]

array([[1.90000000e+01, 5.29591751e+00, 7.60776222e-01, 7.65573144e-01,
        0.00000000e+00],
       [2.00000000e+01, 5.29591751e+00, 7.63159513e-01, 7.65573144e-01,
        0.00000000e+00],
       [2.10000000e+01, 5.29591751e+00, 7.65543044e-01, 7.65573144e-01,
        0.00000000e+00],
       ...,
       [1.57700000e+03, 5.28839874e+00, 7.68409252e-01, 8.13045919e-01,
        1.34368455e+00],
       [1.58000000e+03, 5.28836679e+00, 7.63593376e-01, 8.13245833e-01,
        1.32365930e+00],
       [1.59700000e+03, 5.28830099e+00, 7.61506915e-01, 8.13661993e-01,
        1.31129241e+00]])

In [368]:
print('v_grid:\n', avg_grid)
print('cell_number:\n ', number)
print('maxium velocity:\n', vmax)
print('minium velocity:\n ', vmin)

v_grid:
 [[1.33203121 1.28981434 1.42167348 1.29713952]
 [1.19591927 1.16016655 1.22656303 1.16294695]
 [0.98962555 1.10013083 1.20045936 1.06737435]
 [0.93109469 1.03572915 1.27490416 1.05455427]]
cell_number:
  [[348. 278. 276. 596.]
 [480. 400. 411. 687.]
 [464. 396. 385. 696.]
 [315. 267. 269. 605.]]
maxium velocity:
 [[1.97166526 1.44234371 1.6915195  1.78912997]
 [2.24448967 1.44357419 1.56255078 1.6601609 ]
 [2.35577369 1.49185634 1.51113546 1.51158094]
 [1.36321271 1.23455536 1.43770206 1.43203855]]
minium velocity:
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [386]:
show_box = np.zeros([4,4])
for i in range(len(avg_grid[1,:])):
    for j in range(len(avg_grid[:,1])):
        # row compare
        if j < 3:
            dif = avg_grid[i,j+1]-avg_grid[i,j]
            #print('difference:', dif)
            if dif >=0:
                perct = dif/avg_grid[i,j]
            else:
                perct = abs(dif/avg_grid[i,j+1])
            #print('percentage:',perct)
            if perct > 0.2:
                show_box[i, j] += 1
                show_box[i, j+1] += 1
                print('WARNING zone%s%s, speed:%s, zone%s%s,speed:%s. Difference%%:%s '\
                      %(i, j, avg_grid[i,j], i, j+1, avg_grid[i, j+1], perct )) 
        # col compare
        if i < 3:
            dif = avg_grid[i+1,j]-avg_grid[i,j]
            #print('difference:', dif)
            if dif >=0:
                perct = dif/avg_grid[i,j]
            else:
                perct = abs(dif/avg_grid[i+1,j])
            #print('percentage:',perct)
            if perct > 0.2:
                show_box[i, j] += 1
                show_box[i+1, j] += 1
                print('WARNING zone%s%s, speed:%s, zone%s%s,speed:%s. Difference%%:%s '\
                      %(i, j, avg_grid[i,j], i+1, j, avg_grid[i+1, j], perct )) 
        # prime-diag compare
        if i < 3 and j < 3:
            dif = avg_grid[i+1,j+1]-avg_grid[i,j]
            #print('difference:', dif)
            if dif >=0:
                perct = dif/avg_grid[i,j]
            else:
                perct = abs(dif/avg_grid[i+1,j+1])
            #print('percentage:',perct)
            if perct > 0.2:
                show_box[i, j] += 1
                show_box[i+1, j+1] += 1
                print('WARNING zone%s%s, speed:%s, zone%s%s,speed:%s. Difference%%:%s '\
                      %(i, j, avg_grid[i,j], i+1, j+1, avg_grid[i+1, j+1], perct )) 
        # vice-diag compare
        if i < 3 and j > 0:
            dif = avg_grid[i+1,j-1]-avg_grid[i,j]
            #print('difference:', dif)
            if dif >=0:
                perct = dif/avg_grid[i,j]
            else:
                perct = abs(dif/avg_grid[i+1,j-1])
            #print('percentage:',perct)
            if perct > 0.2:
                show_box[i, j] += 1
                show_box[i+1, j-1] += 1
                print('WARNING zone%s%s, speed:%s, zone%s%s,speed:%s. Difference%%:%s '\
                      %(i, j, avg_grid[i,j], i+1, j-1, avg_grid[i+1, j-1], perct )) 

WARNING zone02, speed:1.4216734827282609, zone13,speed:1.1629469473544396. Difference%:0.2224749254146048 
WARNING zone02, speed:1.4216734827282609, zone11,speed:1.160166549375. Difference%:0.22540464857751571 
WARNING zone10, speed:1.1959192723104166, zone20,speed:0.9896255520967673. Difference%:0.20845633964944105 
WARNING zone31, speed:1.0357291544558052, zone32,speed:1.2749041593791823. Difference%:0.23092427580552657 
WARNING zone32, speed:1.2749041593791823, zone33,speed:1.0545542675596693. Difference%:0.20895073738539974 


In [369]:
for i in range(len(avg_grid[1,:])-1):
    for j in range(len(avg_grid[:,1])-1):
        print(avg_grid[i,j])

1.3320312137068966
1.2898143423021582
1.4216734827282609
1.1959192723104166
1.160166549375
1.2265630319221412
0.9896255520967673
1.100130832227273
1.2004593644857142


In [400]:
print(avg_grid)
visual_box = np.zeros([7,7])
visual_box

[[1.33203121 1.28981434 1.42167348 1.29713952]
 [1.19591927 1.16016655 1.22656303 1.16294695]
 [0.98962555 1.10013083 1.20045936 1.06737435]
 [0.93109469 1.03572915 1.27490416 1.05455427]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [411]:
visual_box[::2,::2] = avg_grid[:,:]
visual_box

array([[1.33203121, 0.        , 1.28981434, 0.        , 1.42167348,
        0.        , 1.29713952],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [1.19591927, 0.        , 1.16016655, 0.        , 1.22656303,
        0.        , 1.16294695],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.98962555, 0.        , 1.10013083, 0.        , 1.20045936,
        0.        , 1.06737435],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.93109469, 0.        , 1.03572915, 0.        , 1.27490416,
        0.        , 1.05455427]])

In [428]:
visual_box[1,0] = -1

visual_str = visual_box.astype(str)
visual_str[visual_str == '-1.0'] = '|'
visual_str

array([['1.3320312137068966', '0.0', '1.2898143423021582', '0.0',
        '1.4216734827282609', '0.0', '1.2971395216255033'],
       ['|', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['1.1959192723104166', '0.0', '1.160166549375', '0.0',
        '1.2265630319221412', '0.0', '1.1629469473544396'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.9896255520967673', '0.0', '1.100130832227273', '0.0',
        '1.2004593644857142', '0.0', '1.06737434726523'],
       ['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
       ['0.9310946888314285', '0.0', '1.0357291544558052', '0.0',
        '1.2749041593791823', '0.0', '1.0545542675596693']], dtype='<U32')

In [443]:
star = np.zeros([4, 4])
list(star)

[array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.])]

In [446]:
test = [[0 for i in range(4)] for j in range(4)]
test

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [10]:
a = 0
if a:
    print('yes')
else:
    print('no')

no
